const CurrentUserActionTypes = {
  LOADING_CURRENT_USER_START: 'LOADING_CURRENT_USER_START',
  LOADING_CURRENT_USER_SUCCESS: 'LOADING_CURRENT_USER_SUCCESS',
  LOADING_CURRENT_USER_FAILURE: 'LOADING_CURRENT_USER_FAILURE',
  SIGN_UP_USER_START: 'SIGN_UP_USER_START',
  SIGN_UP_USER_SUCCESS: 'SIGN_UP_USER_SUCCESS',
  SIGN_UP_USER_FAILURE: 'SIGN_UP_USER_FAILURE',
  SIGN_IN_USER_START: 'SIGN_IN_USER_START',
  SIGN_IN_USER_SUCCESS: 'SIGN_IN_USER_SUCCESS',
  SIGN_IN_USER_FAILURE: 'SIGN_IN_USER_FAILURE',
  SIGN_OUT_USER_START: 'SIGN_OUT_USER_START',
  SIGN_OUT_USER_SUCCESS: 'SIGN_OUT_USER_SUCCESS',
  SIGN_OUT_USER_FAILURE: 'SIGN_OUT_USER_FAILURE'
};

export default CurrentUserActionTypes;
