const UsersListActionTypes = {
  LOADING_USERS_LIST_START: 'LOADING_USERS_LIST_START',
  LOADING_USERS_LIST_SUCCESS: 'LOADING_USERS_LIST_SUCCESS',
  LOADING_USERS_LIST_FAILURE: 'LOADING_USERS_LIST_FAILURE',
  SET_SELECTED_USER: 'SET_SELECTED_USER'
};

export default UsersListActionTypes;
