const SocketEvents = {
  MESSAGE: 'MESSAGE',
  SEND_MESSAGE: 'SEND_MESSAGE',
  LOCATION_MESSAGE: 'LOCATION_MESSAGE',
  SEND_LOCATION: 'SEND_LOCATION',
  FIRST_CONNECTION: 'FIRST_CONNECTION'
};

module.exports = SocketEvents;
