const CurrentChatActionTypes = {
  LOADING_CUURENT_CHAT_START: 'LOADING_CUURENT_CHAT_START',
  LOADING_CUURENT_CHAT_SUCCESS: 'LOADING_CUURENT_CHAT_SUCCESS',
  LOADING_CUURENT_CHAT_FAILURE: 'LOADING_CUURENT_CHAT_FAILURE'
};

export default CurrentChatActionTypes;
